Ftp:
  update_add: /***/****/   ###########服务器端的地址

Local:
  local_add: /****/*****/*****/*****/  #######本地文件上传地址 此处地址为Linux格式

Connection:
  Ip: xxx.xxx.xxx.xxx
  port: 21 #默认端口为21号
  userid: xxxx #ssh连接默认用户名
  pwd: xxxx #ssh连接默认密码

sub:
 subftpname: 2022 #网络存储格式
 sublocname: 2022 #本地存储格式

###################本地文件夹子目录中，最后一集的名字默认按时间+日期命名
###################网络文件夹目录中，最后一级的名字按 2022_+日期命名
